export * from './pageAuth/RegisterPage/RegisterPage'
export * from './pageAuth/LoginPage/LoginPage'
export * from './pageAuth/CarsPage/CarsPage'
export * from './pageAuth/AboutOneCarPage/OneCarPage'
export * from './pageAuth/PrivateCarsPage/PrivateCarsPage'

export * from './pageRegisteredUser/CarsPageReg/CarsPageReg'
export * from './pageRegisteredUser/AboutOneCarPageReg/OneCarPageReg'
export * from './pageRegisteredUser/FavotitCarPage/FavotitCarPage'
export * from './pageRegisteredUser/CreateCarPage/CreateCarPage'
export * from './pageRegisteredUser/MyCarPage/MyCarPage'
export * from './pageRegisteredUser/UpdateCarPage/UpdateCarPage'

export * from './pageManager/ManagerAuthLayout/ManagerAuthLayout'
export * from './pageManager/CarsManaPage/CarsManaPage'
export * from './pageManager/UpdateCarManaPage/UpdateCarManaPage'